// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSend(arg1) {
  return window['go']['main']['App']['CancelSend'](arg1);
}

export function ClearCookies() {
  return window['go']['main']['App']['ClearCookies']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteCookie(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteCookie'](arg1, arg2, arg3);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteTheme(arg1) {
  return window['go']['main']['App']['DeleteTheme'](arg1);
}

export function DuplicateCollection(arg1) {
  return window['go']['main']['App']['DuplicateCollection'](arg1);
}

export function Export(arg1) {
  return window['go']['main']['App']['Export'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetKeybindings() {
  return window['go']['main']['App']['GetKeybindings']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function Import() {
  return window['go']['main']['App']['Import']();
}

export function ImportTheme() {
  return window['go']['main']['App']['ImportTheme']();
}

export function ListCookies() {
  return window['go']['main']['App']['ListCookies']();
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function NewCollection(arg1) {
  return window['go']['main']['App']['NewCollection'](arg1);
}

export function NewEnvironment(arg1, arg2) {
  return window['go']['main']['App']['NewEnvironment'](arg1, arg2);
}

export function OpenCollection(arg1) {
  return window['go']['main']['App']['OpenCollection'](arg1);
}

export function OpenEnvironment(arg1) {
  return window['go']['main']['App']['OpenEnvironment'](arg1);
}

export function OpenKeybindings() {
  return window['go']['main']['App']['OpenKeybindings']();
}

export function ParseCurl(arg1) {
  return window['go']['main']['App']['ParseCurl'](arg1);
}

export function PickFile(arg1) {
  return window['go']['main']['App']['PickFile'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function SaveCollection(arg1, arg2) {
  return window['go']['main']['App']['SaveCollection'](arg1, arg2);
}

export function SaveCookie(arg1) {
  return window['go']['main']['App']['SaveCookie'](arg1);
}

export function SaveEnvironment(arg1, arg2) {
  return window['go']['main']['App']['SaveEnvironment'](arg1, arg2);
}

export function SaveLastBody() {
  return window['go']['main']['App']['SaveLastBody']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}

export function SetUnsaved(arg1) {
  return window['go']['main']['App']['SetUnsaved'](arg1);
}

export function Snippet(arg1, arg2) {
  return window['go']['main']['App']['Snippet'](arg1, arg2);
}

export function SnippetLangs() {
  return window['go']['main']['App']['SnippetLangs']();
}

export function StopRun() {
  return window['go']['main']['App']['StopRun']();
}

export function WSClose(arg1) {
  return window['go']['main']['App']['WSClose'](arg1);
}

export function WSConnect(arg1, arg2) {
  return window['go']['main']['App']['WSConnect'](arg1, arg2);
}

export function WSSend(arg1, arg2) {
  return window['go']['main']['App']['WSSend'](arg1, arg2);
}
