// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {history} from '../models';
import {httpx} from '../models';
import {jsontext} from '../models';
import {collection} from '../models';

export function ClearCookies():Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteCookie(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteHistory(arg1:string):Promise<void>;

export function DeleteTheme(arg1:string):Promise<void>;

export function DuplicateCollection(arg1:string):Promise<main.FileRef>;

export function Export(arg1:string):Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetHistory():Promise<Array<history.Entry>>;

export function GetKeybindings():Promise<main.TextFile>;

export function GetSettings():Promise<main.Settings>;

export function GetWorkspace():Promise<main.Workspace>;

export function Import():Promise<Array<main.FileRef>>;

export function ImportTheme():Promise<main.TextFile>;

export function ListCookies():Promise<Array<httpx.Cookie>>;

export function ListThemes():Promise<Array<main.TextFile>>;

export function NewCollection(arg1:string):Promise<main.FileRef>;

export function NewEnvironment(arg1:string,arg2:string):Promise<main.FileRef>;

export function OpenCollection(arg1:string):Promise<jsontext.Value>;

export function OpenEnvironment(arg1:string):Promise<collection.Environment>;

export function OpenKeybindings():Promise<void>;

export function ParseCurl(arg1:string):Promise<collection.Item>;

export function PickFile(arg1:string):Promise<string>;

export function QuitApp():Promise<void>;

export function Run(arg1:main.RunInput):Promise<void>;

export function SaveCollection(arg1:string,arg2:jsontext.Value):Promise<void>;

export function SaveCookie(arg1:httpx.Cookie):Promise<void>;

export function SaveEnvironment(arg1:string,arg2:collection.Environment):Promise<void>;

export function SaveLastBody():Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function Send(arg1:main.SendInput):Promise<main.SendResult>;

export function SetUnsaved(arg1:boolean):Promise<void>;

export function Snippet(arg1:main.SendInput,arg2:string):Promise<string>;

export function SnippetLangs():Promise<Array<string>>;

export function StopRun():Promise<void>;

export function WSClose(arg1:string):Promise<void>;

export function WSConnect(arg1:string,arg2:main.SendInput):Promise<void>;

export function WSSend(arg1:string,arg2:string):Promise<void>;
